# This is a basic workflow to help you get started with Actions

name: Build RenPy project distributions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Ren'Py
        run: |
          pwd && ls
          wget http://www.renpy.org/dl/7.4.1/renpy-7.4.1-sdk.tar.bz2
          tar xf renpy-7.4.1-sdk.tar.bz2
          rm renpy-7.4.1-sdk.tar.bz2
          mkdir dist
          mv renpy-7.4.1-sdk dist/renpy
          pwd && ls
          ls dist
      - name: Build distributions
        # ./renpy.sh launcher android_build ../.. assembleRelease --dest ..
        run: |
          pwd && ls
          cd dist/renpy
          echo "renpy folder"
          ls
          ./renpy.sh launcher distribute ../..
          pwd && ls
          cd ../..
          echo "main"
          pwd && ls
