# This is a basic workflow to help you get started with Actions

name: Build RenPy project distributions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build distributions
        uses: ProjectAliceDev/renpy-build-action@v1.1.2
        with:
          sdk-version: "7.4.1"
        env:
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy
