# This is a basic workflow to help you get started with Actions

name: Build Desktop distributions

on:
  push:
    tags:
      - "*"
    branches: [ci]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Ren'Py
        run: |
          pwd && ls
          wget --no-verbose http://www.renpy.org/dl/7.4.1/renpy-7.4.1-sdk.tar.bz2
          tar xf renpy-7.4.1-sdk.tar.bz2
          rm renpy-7.4.1-sdk.tar.bz2
          mv renpy-7.4.1-sdk ../renpy
      - name: Build distributions
        # ./renpy.sh launcher android_build ../.. assembleRelease --dest ..
        run: |
          pwd && ls
          echo "renpy folder"
          cd ../renpy
          ./renpy.sh launcher distribute ../coalescence --destination ../coalescence/dist
      - name: Upload game artifact
        id: uploadArtifact
        uses: actions/upload-artifact@v1
        with:
          name: Coalescence PC
          path: dist/Coalescence-0.99.9-pc.zip
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.COALESCENCE_RELEASE_KEY }}
