name: Build Desktop distributions

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Renpy Folder
        uses: actions/cache@v2
        id: cache-renpy
        env:
          cache-name: cache-renpy
        with:
          path: /home/runner/work/coalescence/renpy
          key: ${{ runner.os }}-cache-renpy
          restore-keys: |
            ${{ runner.os }}-cache-renpy
      - name: Install Ren'Py
        if: steps.cache-renpy.outputs.cache-hit != 'true'
        run: |
          wget --no-verbose http://www.renpy.org/dl/7.4.2/renpy-7.4.2-sdk.tar.bz2
          mv renpy-7.4.2-sdk.tar.bz2 /home/runner/work/coalescence
      - name: Upload Renpy Folder
        uses: actions/upload-artifact@v2
        with:
          name: renpy
          path: /home/runner/work/coalescence/renpy-7.4.2-sdk.tar.bz2

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Renpy artifact
        uses: actions/download-artifact@v2
        with:
          name: renpy
      - name: Extract renpy files
        run: |
          tar xf renpy-7.4.2-sdk.tar.bz2
          mv renpy-7.4.2-sdk /home/runner/work/coalescence/renpy
          rm renpy-7.4.2-sdk.tar.bz2
      - name: Lint game
        run: |
          cd /home/runner/work/coalescence/renpy
          ./renpy.sh ../coalescence lint > ../coalescence/dist/report.txt
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: /home/runner/work/coalescence/coalescence/dist/report.txt

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Renpy artifact
        uses: actions/download-artifact@v2
        with:
          name: renpy
      - name: Extract renpy files
        run: |
          tar xf renpy-7.4.2-sdk.tar.bz2
          mv renpy-7.4.2-sdk /home/runner/work/coalescence/renpy
          rm renpy-7.4.2-sdk.tar.bz2
      - name: Build distributions
        run: |
          cd /home/runner/work/coalescence/renpy
          ./renpy.sh launcher distribute ../coalescence --destination ../coalescence/dist
      - name: Upload distributions
        uses: actions/upload-artifact@v2
        with:
          name: distributions
          path: /home/runner/work/coalescence/coalescence/dist

  release:
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download report
        uses: actions/download-artifact@v2
        with:
          name: report
      - name: Download distributions
        uses: actions/download-artifact@v2
        with:
          name: distributions
      - name: Check
        run: |
          echo "kinda home"
          pwd
          ls
          echo " going into dist"
          mv report.txt Coalescence-* dist
          cd /home/runner/work/coalescence/coalescence/dist
          ls

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.COALESCENCE_RELEASE_KEY }}
