name: Build Desktop distributions

on:
  push:
    tags:
      - "*"
    branches: [ci]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Ren'Py
        run: |
          pwd && ls
          wget --no-verbose http://www.renpy.org/dl/7.4.1/renpy-7.4.1-sdk.tar.bz2
          tar xf renpy-7.4.1-sdk.tar.bz2
          rm renpy-7.4.1-sdk.tar.bz2
          mv renpy-7.4.1-sdk ../renpy
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint game
        run: |
          pwd && ls
          cd ..
          echo "kinda home"
          ls
          echo " going into renpy folder"
          cd renpy
          ls
          ./renpy.sh ../coalescence lint > ../coalescence/dist/report.txt

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build distributions
        run: |
          pwd && ls
          cd ..
          echo "kinda home"
          ls
          echo "renpy folder"
          cd renpy
          ./renpy.sh launcher distribute ../coalescence --destination ../coalescence/dist
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.COALESCENCE_RELEASE_KEY }}
