name: Build Desktop distributions

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Renpy Folder
        uses: actions/cache@v2
        id: cache-renpy
        env:
          cache-name: cache-renpy
        with:
          path: /home/runner/work/coalescence/renpy
          key: ${{ runner.os }}-cache-renpy
          restore-keys: |
            ${{ runner.os }}-cache-renpy

      - name: Install Ren'Py
        if: steps.cache-renpy.outputs.cache-hit != 'true'
        run: |
          wget --no-verbose http://www.renpy.org/dl/7.4.1/renpy-7.4.1-sdk.tar.bz2
          tar xf renpy-7.4.1-sdk.tar.bz2
          rm renpy-7.4.1-sdk.tar.bz2
          mv renpy-7.4.1-sdk /home/runner/work/coalescence/renpy

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint game
        run: |
          cd /home/runner/work/coalescence/
          echo "kinda home"
          ls
          echo " going into renpy folder"
          cd renpy
          ls
          ./renpy.sh ../coalescence lint > ../coalescence/dist/report.txt

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build distributions
        run: |
          cd /home/runner/work/coalescence/
          echo "kinda home"
          ls
          echo " going into renpy folder"
          cd renpy
          ls
          ./renpy.sh launcher distribute ../coalescence --destination ../coalescence/dist
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.COALESCENCE_RELEASE_KEY }}
